spring:
  data:
    rest:
      basePath: /api
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
security:
  ignored: '/assets/**'

