# H2
spring:
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:h2:file:${H2_FILENAME};DB_CLOSE_ON_EXIT=FALSE
    username: 'sa'
    password: 'sa'
    driver-class-name: 'org.h2.Driver'
