# H2
spring:
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:h2:tcp://localhost:9092/~/bgp
    username: 'sa'
    password: ''
    driver-class-name: 'org.h2.Driver'

# Enable to debug connection leak issues
#    hikari:
#      leak-detection-threshold: 20000
#      idle-timeout: 10000
#      max-lifetime: 30000