spring:
  ssl:
    bundle:
      jks:
        web-server:
          key:
            alias: "${SSL_KEY_ALIAS}"
          keystore:
            location: "file:${SSL_KEYSTORE_FILE}"
            password: "${SSL_KEYSTORE_PASSWORD}"
server:
  port: 8443
  ssl:
    bundle: "web-server"
